### ISSUE TITLE
URL-Playback via msg.url-Input

### ISSUE THREAD

**Issue by Bond246** [bartbutenaers/node-red-contrib-ui-mp4-player#1]
Hello,

very big thanks for this plugin.

One thing i really would appreciate is to change the playback-URL with a input-message. We have multible playback streams that should be monitored but with just one player-widget and i would like to start playback with button-controls.

Thanks
Florian

**Comment by Bond246** [comment]
I found what i was looking for.
To do so msg.topic has to be "set_source". :-)

**Comment by bartbutenaers** [comment]
Hi @Bond246,
Glad to hear to you find a solution already by yourself!
Notice that I quickly developed this node, only to [help](https://discourse.nodered.org/t/media-source-extension-video-player-for-live-streaming-mp4/31958/18?u=bartbutenaers) Kevin Godell developing his first Node-RED UI node.
Meanwhile he his [node-red-contrib-ui-mp4frag](https://github.com/kevinGodell/node-red-contrib-ui-mp4frag) node is much more advanced compared to mine.
I have only spend about 1 hour on my node, and I am not going to maintain it further.  
So I suggest you to start using Kevin's node!
Bart
